### ISSUE TITLE
Something somewhere being mistaken after timeout

### ISSUE THREAD

**Issue by dragmine149** [dragmine149/DBJ7#6]
Error log

```
[2022/10/05 21:04:50] - [ERROR] [discord.ui.view] Ignoring exception in view <Multiple_Buttons timeout=180.0 children=2> for item <Button style=<ButtonStyle.success: 3> url=None disabled=False label='yes' emoji=<PartialEmoji animated=False name='✅' id=None> row=None>
Traceback (most recent call last):
  File "/home/drag/.cache/pypoetry/virtualenvs/dbj7-E_APj_fw-py3.9/lib/python3.9/site-packages/discord/ui/view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "/mnt/d/Code/DBJ7/src/utils/uis.py", line 40, in callback
    await self.callbackFunc(Interaction, self.label)
  File "/mnt/d/Code/DBJ7/src/utils/MoneySelector.py", line 103, in confirmCallback
    return await self.callback(self.value)
  File "/mnt/d/Code/DBJ7/src/games/flip_coin.py", line 103, in money_callback
    await self.pre_game()
  File "/mnt/d/Code/DBJ7/src/games/flip_coin.py", line 122, in pre_game
    self.choosen = Coin_State(view.choosen.label.lower())
  File "/home/drag/.cache/pypoetry/virtualenvs/dbj7-E_APj_fw-py3.9/lib/python3.9/site-packages/aenum/__init__.py", line 2656, in __call__
    return cls.__new__(cls, value)
  File "/home/drag/.cache/pypoetry/virtualenvs/dbj7-E_APj_fw-py3.9/lib/python3.9/site-packages/aenum/__init__.py", line 3090, in __new__
    raise ve_exc
ValueError: 'play game!' is not a valid Coin_State
```

**Comment by JojoDEVAAA** [comment]
@dragmine149 Have you been able to solved your issue?

**Comment by timelessnesses** [comment]
I will try fix this

**Comment by timelessnesses** [comment]
Wait why it's view.choosen instead of label.lower

**Comment by timelessnesses** [comment]
who even is @JojoDEVAAA

**Comment by timelessnesses** [comment]
gyze

**Comment by dragmine149** [comment]
[6ee42be](https://github.com/dragmine149/DBJ7/commit/6ee42bec2bd33a4cbfe65da676b9c5637dc67a17) fix
